mtcars : Motor Trend Car Road Tests

In [172]:
# 데이터 파일 읽기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

x_train = pd.read_csv("/content/mpg_X_train.csv")
x_test = pd.read_csv("/content/mpg_X_test.csv")
y_train = pd.read_csv("/content/mpg_y_train.csv")

In [173]:
# 데이터 전처리
x_train.shape

(278, 8)

In [174]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          278 non-null    object 
 1   mpg           278 non-null    float64
 2   cylinders     278 non-null    int64  
 3   displacement  278 non-null    float64
 4   horsepower    274 non-null    float64
 5   weight        278 non-null    int64  
 6   acceleration  278 non-null    float64
 7   model_year    278 non-null    int64  
dtypes: float64(4), int64(3), object(1)
memory usage: 17.5+ KB


In [175]:
x_train.horsepower # Series

0       85.0
1      175.0
2       68.0
3      180.0
4       88.0
       ...  
273     60.0
274     67.0
275     83.0
276     97.0
277    150.0
Name: horsepower, Length: 278, dtype: float64

In [176]:
x_train.horsepower.shape # 1차원

(278,)

In [177]:
x_train[['horsepower']] # dataframe

horsepower
0          85.0
1         175.0
2          68.0
3         180.0
4          88.0
..          ...
273        60.0
274        67.0
275        83.0
276        97.0
277       150.0

[278 rows x 1 columns]

In [178]:
x_train[['horsepower']].isnull().sum()

horsepower    4
dtype: int64

In [179]:
x_train[['horsepower']].shape # 2차원

(278, 1)

In [180]:
# 결측치 대체 : 평균값 대체
# SimpleImputer

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x_train[['horsepower']] = imputer.fit_transform(x_train[['horsepower']])

In [181]:
x_train[['horsepower']].isnull().sum()

horsepower    0
dtype: int64

In [182]:
x_test[['horsepower']] = imputer.fit_transform(x_test[['horsepower']])

In [183]:
x_test[['horsepower']].isnull().sum()

horsepower    0
dtype: int64

In [184]:
# 요약통계량

x_train.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  278.000000  278.000000    278.000000  278.000000   278.000000   
mean    23.732734    5.374101    189.994604  103.383212  2948.464029   
std      7.647295    1.677084    105.471423   38.695458   862.949746   
min     10.000000    3.000000     68.000000   46.000000  1613.000000   
25%     18.000000    4.000000     98.000000   75.000000  2206.250000   
50%     23.000000    4.000000    140.500000   90.500000  2737.500000   
75%     29.000000    6.000000    258.000000  118.750000  3560.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    278.000000  278.000000  
mean      15.580216   76.057554  
std        2.745907    3.605591  
min        8.000000   70.000000  
25%       14.000000   73.000000  
50%       15.500000   76.000000  
75%       17.000000   79.000000  
max       24.800000   82.000000

In [185]:
x_train[:3]

name   mpg  cylinders  displacement  horsepower  \
0  pontiac j2000 se hatchback  31.0          4         112.0        85.0   
1         pontiac safari (sw)  13.0          8         400.0       175.0   
2          mazda glc custom l  37.0          4          91.0        68.0   

   weight  acceleration  model_year  
0    2575          16.2          82  
1    5140          12.0          71  
2    2025          18.2          82

In [186]:
x_train.columns

Index(['name', 'mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year'],
      dtype='object')

In [187]:
col_del = ['name']
col_num = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year']
col_cat = []
col_y = ['isUSA']

In [188]:
x_train = x_train.iloc[:, 1:]
x_test = x_test.iloc[:, 1:]

In [189]:
x_train.head(1)

mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  31.0          4         112.0        85.0    2575          16.2          82

In [190]:
x_test.head(1)

mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  34.1          4          86.0        65.0    1975          15.2          79

In [191]:
x_train

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    31.0          4         112.0        85.0    2575          16.2   
1    13.0          8         400.0       175.0    5140          12.0   
2    37.0          4          91.0        68.0    2025          18.2   
3    12.0          8         350.0       180.0    4499          12.5   
4    19.0          4         120.0        88.0    3270          21.9   
..    ...        ...           ...         ...     ...           ...   
273  36.1          4          91.0        60.0    1800          16.4   
274  30.0          4          97.0        67.0    1985          16.4   
275  33.5          4          98.0        83.0    2075          15.9   
276  18.0          6         171.0        97.0    2984          14.5   
277  17.0          8         304.0       150.0    3672          11.5   

     model_year  
0            82  
1            71  
2            82  
3            73  
4            76  
..          ...  
273          78  
274          77  
275          77  
276          75  
277          72  

[278 rows x 7 columns]

In [192]:
x_train[col_num]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    31.0          4         112.0        85.0    2575          16.2   
1    13.0          8         400.0       175.0    5140          12.0   
2    37.0          4          91.0        68.0    2025          18.2   
3    12.0          8         350.0       180.0    4499          12.5   
4    19.0          4         120.0        88.0    3270          21.9   
..    ...        ...           ...         ...     ...           ...   
273  36.1          4          91.0        60.0    1800          16.4   
274  30.0          4          97.0        67.0    1985          16.4   
275  33.5          4          98.0        83.0    2075          15.9   
276  18.0          6         171.0        97.0    2984          14.5   
277  17.0          8         304.0       150.0    3672          11.5   

     model_year  
0            82  
1            71  
2            82  
3            73  
4            76  
..          ...  
273          78  
274          77  
275          77  
276          75  
277          72  

[278 rows x 7 columns]

In [193]:
# 데이터 모델링(모형 구축) >> train (tr / val)

from sklearn.model_selection import train_test_split

x_tr, x_val, y_tr, y_val=train_test_split(x_train, y_train, test_size=0.3)

In [194]:
print(x_tr.shape)
print(x_val.shape)

print(y_tr.shape)
print(y_val.shape)

(194, 7)
(84, 7)
(194, 1)
(84, 1)


In [195]:
x_tr.head(3)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
122  18.0          3          70.0        90.0    2124          13.5   
272  20.2          6         200.0        88.0    3060          17.1   
236  15.5          8         400.0       190.0    4325          12.2   

     model_year  
122          73  
272          81  
236          77

In [196]:
x_tr[col_num][:3]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
122  18.0          3          70.0        90.0    2124          13.5   
272  20.2          6         200.0        88.0    3060          17.1   
236  15.5          8         400.0       190.0    4325          12.2   

     model_year  
122          73  
272          81  
236          77

In [197]:
y_tr.head(3)

isUSA
122      0
272      1
236      1

In [198]:
y_tr.shape

(194, 1)

In [199]:
y_tr.values[:3]

array([[0],
       [1],
       [1]])

In [200]:
y_tr.values.shape # 2차원

(194, 1)

In [201]:
y_tr.values.ravel()

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1])

In [202]:
# 정규화 (Scailing)
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()
# scaler.fit(x_tr[col_num])

# x_tr[col_num] = scaler.transform(x_tr[col_num])
# x_val[col_num] = scaler.transform(x_val[col_num])
# x_test[col_num] = scaler.transform(x_test[col_num])

In [203]:
# 정규화 (Scailing)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_tr)

x_tr = scaler.transform(x_tr)
x_val = scaler.transform(x_val)
x_test = scaler.transform(x_test)

In [204]:
# 모델링 KNN

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn.fit(x_tr, y_tr.values.ravel())

KNeighborsClassifier(metric='euclidean')

In [205]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=10)
dt.fit(x_tr, y_tr)

DecisionTreeClassifier(max_depth=10)

In [206]:
# 모델 평가
pred_val = knn.predict(x_val)

In [207]:
pred_val

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1])

In [208]:
pred_val_proba_knn = knn.predict_proba(x_val)
pred_val_proba_dt = dt.predict_proba(x_val)

In [209]:
pred_val_proba_knn[:3]

array([[1. , 0. ],
       [0. , 1. ],
       [0.8, 0.2]])

In [210]:
# roc_auc

from sklearn.metrics import roc_auc_score

score_knn = roc_auc_score(y_val, pred_val_proba_knn[:, 1])
score_dt = roc_auc_score(y_val, pred_val_proba_dt[:, 1])

print(score_knn, score_dt)

0.8901399878271455 0.8910529519172247


In [218]:
best_model = None
best_score = 0

for i in range(2, 10):
    model = KNeighborsClassifier(n_neighbors=i, metric='euclidean')
    model.fit(x_tr, y_tr.values.ravel())
    pred_val_proba = model.predict_proba(x_val)
    score = roc_auc_score(y_val,pred_val_proba [:, 1])
    print(i, '개의 이웃 확인: ', score)
    if best_score <= score:
        best_model = model
        best_score = score

2 개의 이웃 확인:  0.8989653073645771
3 개의 이웃 확인:  0.8962264150943396
4 개의 이웃 확인:  0.8895313451004261
5 개의 이웃 확인:  0.8901399878271455
6 개의 이웃 확인:  0.9023128423615338
7 개의 이웃 확인:  0.9026171637248934
8 개의 이웃 확인:  0.9004869141813755
9 개의 이웃 확인:  0.8913572732805843


In [219]:
print(best_model)

KNeighborsClassifier(metric='euclidean', n_neighbors=7)


In [220]:
print(best_score)

0.9026171637248934


In [223]:
best_model.predict_proba(x_test)[:3]

array([[0.57142857, 0.42857143],
       [0.14285714, 0.85714286],
       [0.        , 1.        ]])

In [224]:
pred =- best_model.predict_proba(x_test)[:,1]
print(pred)

[-0.42857143 -0.85714286 -1.         -1.         -0.42857143 -0.28571429
 -0.42857143 -0.28571429 -0.28571429 -0.57142857 -1.         -0.42857143
 -1.         -0.85714286 -0.14285714 -0.14285714 -1.         -1.
 -0.14285714 -1.         -1.         -1.         -1.         -1.
 -1.         -0.28571429 -0.14285714 -1.         -1.         -0.57142857
 -0.14285714 -0.14285714 -0.71428571 -0.71428571 -1.         -0.71428571
 -0.71428571 -1.         -0.14285714 -0.57142857 -1.         -0.14285714
 -0.         -0.57142857 -0.28571429 -0.42857143 -0.14285714 -1.
 -0.28571429 -1.         -0.         -0.28571429 -1.         -0.28571429
 -1.         -1.         -1.         -0.71428571 -1.         -0.28571429
 -1.         -0.71428571 -1.         -1.         -0.71428571 -1.
 -1.         -0.28571429 -0.85714286 -0.14285714 -1.         -1.
 -0.71428571 -0.         -1.         -0.28571429 -1.         -0.28571429
 -0.28571429 -1.         -1.         -1.         -0.14285714 -1.
 -1.         -1.         -

In [225]:
pd.DataFrame({'isUSA': pred})

isUSA
0   -0.428571
1   -0.857143
2   -1.000000
3   -1.000000
4   -0.428571
..        ...
115 -0.000000
116 -1.000000
117 -1.000000
118 -1.000000
119 -0.000000

[120 rows x 1 columns]

In [226]:
pd.DataFrame({'isUSA': pred}).to_csv('./mtcars_res.csv', index=False)