# PyTorch Tensor Manipulations

In [1]:
import torch

## Tensor Shaping

### reshape: Change Tensor Shape

In [3]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x)
print(x.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])


In [4]:
print(x.reshape(12)) 
# 12 = 3 * 2 * 2 >> 1차원 
print(x.reshape(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [5]:
print(x.reshape(3, 4)) 
# 3 * 4 = (3 * 2 * 2) >> 2차원 
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [6]:
print(x.reshape(3, 1, 4))
# 12 = 3*1*4 >> 3차원 
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [6]:
print(x.reshape(3, 2, 2, 1))
# 12 = 3*2*2*1 >> 4차원 

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


You can use 'view()' instead of 'reshape()' in some cases.

- https://pytorch.org/docs/stable/tensor_view.html
- https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view

### squeeze: Remove dimension which has only one element.

In [7]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])

print(x)
print(x.size())

tensor([[[1., 2.],
         [3., 4.]]])
torch.Size([1, 2, 2])


Remove any dimension which has only one element.

In [8]:
# 1인 차원 제거 
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


Remove certain dimension, if it has only one element.
If it is not, there would be no change.

In [10]:
print(x)
print(x.squeeze(0).size())
# 0번 index '1' 존재 >> squeeze 가능 
print(x.squeeze(1).size())
# 1번 index '1' 존재 하지 않음 >> squeeze 불가능

tensor([[[1., 2.],
         [3., 4.]]])
torch.Size([2, 2])
torch.Size([1, 2, 2])


### unsqueeze: Insert dimension at certain index.

In [11]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

print(x)
print(x.size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [14]:
# unsqueeze() : 특정 dimension에 '1' 더함 
print(x.unsqueeze(2)) 
# 3번째 dimension에 '1' 첨가 
print(x.unsqueeze(2).size())

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
torch.Size([2, 2, 1])


In [15]:
print(x.unsqueeze(-1))
print(x.unsqueeze(-1).size())

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
torch.Size([2, 2, 1])


In [16]:
print(x.reshape(2, 2, -1))

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
