In [1]:
# 배열 만들기

list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
print(np.array([3,1.4,2,3,4.5]))

# numpy array는 단일 데이터 타입
# 정수, 실수 혼용 >> 실수로 변경됨

[3.  1.4 2.  3.  4.5]


In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
print(np.array([1,2,3,4]))
print()
print(np.array([1,2,3,4], dtype=float))
# dtype 옵션 : data type 명시

print()
arr = np.array([1,2,3,4], dtype=float)
print(arr)
print(arr.dtype)

# astype() : 데이터 타입 변경
print(arr.astype(int))

[1 2 3 4]

[1. 2. 3. 4.]

[1. 2. 3. 4.]
float64
[1 2 3 4]


In [12]:
# np.zeros()
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# np.ones()
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# np.arange(start, stop, step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# np.linspace() : n 빵
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# 난수 활용, 배열 만들기

np.random.random((2,2))
# 0~1 사이 균일 분포 난수 생성
# (2,2) : size >> 튜플형태로 매개변수로 받아서 난수 생성

array([[0.73280117, 0.31911525],
       [0.3405253 , 0.56986182]])

In [19]:
# 도와주세요.

# np.random.random이 np.random.rand 하고 같은건가요?

np.random.rand(2,2)
# # 0~1 사이 균일 분포 난수 생성
# 직접 차원(2,2) 인수를 넣어줌
# rand를 더 많이 사용함

array([[0.28099367, 0.58318337],
       [0.17117656, 0.40037682]])

In [23]:
# normal(평균, 표준편차, 매개변수(튜플))
# 정규분포 형태, 매개변수를 튜플로 받아서 난수 생성
np.random.normal(0,1,(2,2))


array([[ 0.54522641, -0.23859707],
       [-1.39747449, -0.09785762]])

In [24]:
# randn()
np.random.randn(2,2)
# 2*2 크기의 배열을 직접 생성

array([[ 0.03969491,  1.31497992],
       [-1.58690691,  0.77920113]])

In [26]:
np.random.randint(0,10,(2,2))
# 0 에서부터 9(n-1) 까지 숫자 범위에서 
# 정수로 이루어진 (2,2) 행렬 생성

array([[9, 5],
       [1, 1]])

In [28]:
# 배열의 기초
np.random.randint(10, size=(3,4))
# 10 : 최댓값, 명시 안하면 최소값 0

array([[0, 9, 6, 2],
       [8, 1, 8, 1],
       [5, 5, 5, 0]])

In [32]:
x = np.random.randint(10, size=(3,4))

print(x.ndim) # 2 >> 차원
print(x.shape) # (3,4) 행렬 (형태)
print(x.size) # 12 >> 크기(원소의 개수)
print(x.dtype) # int32 (정수) 데이터 타입

2
(3, 4)
12
int32


In [33]:
# indexing 과 slicing

np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [35]:
# indexing

a = np.arange(7)

print(a[3])
print(a[-3])

3
4


In [36]:
a[0] = 10
print(a)

[10  1  2  3  4  5  6]


In [42]:
# slicing

print(a)
print()
print(a[1:4])
print()
print(a[1:])
print()
print(a[::2]) # interval이 2칸씩
print(a[::-1]) # 역순 (***)

[10  1  2  3  4  5  6]

[1 2 3]

[1 2 3 4 5 6]

[10  2  4  6]
[ 6  5  4  3  2  1 10]


In [51]:
# reshape() : 형태 변경 (****)

x = np.arange(8)
print(x)
print()

print(x.shape) # 1차원 (8개 원소)
print()

x2 = x.reshape(2,4) # 2차원 (2,4) 행렬로 변환
print(x2)
print(x2.shape)

[0 1 2 3 4 5 6 7]

(8,)

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)


In [55]:
# 이어 붙이고 나누기 작업

# 이어 붙이기 >> concatenate : array 이어 붙임

x1 = np.array([0,1,2])
x2 = np.array([3,4,5])

print(x1)
print()
print(x2)
print()

np.concatenate([x1,x2])

[0 1 2]

[3 4 5]



array([0, 1, 2, 3, 4, 5])

In [61]:
# concatenate >> axis 축 기준 이어 붙이기

m = np.arange(4).reshape(2,2)

print(m)
print()
print(np.concatenate([m,m]))
print()
print(np.concatenate([m,m],axis=0))
# axis=0 (defualt, 설정된 기본값)
print()
print(np.concatenate([m,m],axis=1))

[[0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1]
 [2 3]
 [0 1]
 [2 3]]

[[0 1 0 1]
 [2 3 2 3]]


In [65]:
#  나누기 split()
np.arange(16).reshape(4,4)

m = np.arange(16).reshape(4,4)
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [66]:
print(np.split(m, [3], axis=0))

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [68]:
m1, m2 = np.split(m, [3], axis=0)

print(m1)
print()
print(m2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [70]:
print(np.split(m, [3], axis=1))

[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [69]:
m3, m4 = np.split(m, [3], axis=1)

print(m3)
print()
print(m4)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]

[[ 3]
 [ 7]
 [11]
 [15]]


넘파이 연산

In [78]:
# array 의 모든 원소에 5를 더하는 함수 생성

import numpy as np 

def 더하기_5(values):
    output = np.empty(len(values)) 
    
    for i in range(len(values)):
        output[i] = values[i] + 5
    return output

values = np.random.randint(1, 10, size=5) 

print(values)
print()
print(더하기_5(values))


[6 2 7 9 3]

[11.  7. 12. 14.  8.]


In [72]:
np.empty(5)
# 5개의 원소를 가진 1차원 배열 생성 
# 초기화는 되어 있지 않음
# >> 여기에 출력되는 값은 메모리에 이미 존재한 임의의 값으로 배열 채움

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [79]:
# loop vs numpy

big_arr = np.random.randint(1,10,size=100000)

더하기_5(big_arr)

array([13.,  9.,  7., ..., 13.,  7., 12.])

In [80]:
big_arr + 5 # rodacasting 되어 계산 >> 헐. 훨씬 빠르네

array([13,  9,  7, ..., 13,  7, 12])

In [81]:
# 기본 연산

np.arange(4)

array([0, 1, 2, 3])

In [82]:
x = np.arange(4)

print(x+5)
print(x-5)
print(x*5)
print(x/5)

[5 6 7 8]
[-5 -4 -3 -2]
[ 0  5 10 15]
[0.  0.2 0.4 0.6]


In [85]:
# 행렬 간 연산

x = np.arange(4).reshape((2,2))

y = np.random.randint(10,size=(2,2))

print(x+y)
print()
print(x-y)

[[ 2  3]
 [10  7]]

[[-2 -1]
 [-6 -1]]


In [87]:
# 브로드캐스팅(BroadCasting)

print(x)
print()
print(x+5)

[[0 1]
 [2 3]]

[[5 6]
 [7 8]]


In [88]:
# 집계함수

np.arange(8).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
x = np.arange(8).reshape((2,4))
 
print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))

28
0
7
3.5


In [92]:
# axis 사용, 집계하기

print(x)
print()
print(np.sum(x, axis=0))
print()
print(np.sum(x, axis=1))

[[0 1 2 3]
 [4 5 6 7]]

[ 4  6  8 10]

[ 6 22]


In [93]:
# 마스킹(masking) 연산 (조건 연산자 >> True, False)

np.arange(5)

array([0, 1, 2, 3, 4])

In [94]:
x = np.arange(5)

print(x<3)
print()
print(x>5)

[ True  True  True False False]

[False False False False False]


In [95]:
x[x<3]

array([0, 1, 2])

In [96]:
condition = (x<3)

x[condition]

array([0, 1, 2])